// ---------------------------------------------------------------------------
// Markdown report generator
// ---------------------------------------------------------------------------

import type { ReportInput } from '../report-engine.js';

export function generateMarkdownReport(input: ReportInput): string {
  const { summary, findings, correlatedGroups, scanId, targetName, scanDate, reportType, validation } = input;
  const lines: string[] = [];

  lines.push(`# SecureScope Security Report`);
  lines.push('');
  lines.push(`**Target:** ${targetName}  `);
  lines.push(`**Scan ID:** ${scanId.slice(0, 8)}  `);
  lines.push(`**Report Type:** ${reportType}  `);
  lines.push(`**Scan Date:** ${scanDate}  `);
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Findings | ${summary.total_findings} |`);
  lines.push(`| Critical | ${summary.critical} |`);
  lines.push(`| High | ${summary.high} |`);
  lines.push(`| Medium | ${summary.medium} |`);
  lines.push(`| Low | ${summary.low} |`);
  lines.push(`| Informational | ${summary.informational} |`);
  lines.push(`| Auto-fixable | ${summary.autofixable} |`);
  lines.push('');

  // Correlated groups
  if (correlatedGroups.length > 0) {
    lines.push('## Correlated Risk Groups');
    lines.push('');
    for (const group of correlatedGroups) {
      lines.push(`### ${group.combined_severity.toUpperCase()}: ${group.title}`);
      lines.push('');
      lines.push(group.description);
      lines.push('');
      lines.push(`**Rationale:** ${group.rationale}`);
      lines.push('');
      lines.push(`*${group.finding_ids.length} findings correlated*`);
      lines.push('');
    }
  }

  // Validation
  if (validation) {
    lines.push('## Validation Results');
    lines.push('');
    lines.push(`| Status | Count |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Fixed | ${validation.fixed} |`);
    lines.push(`| Partially Mitigated | ${validation.partially_mitigated} |`);
    lines.push(`| Unchanged | ${validation.unchanged} |`);
    lines.push(`| Regressed | ${validation.regressed} |`);
    lines.push(`| New Findings | ${validation.new_findings} |`);
    lines.push('');
  }

  // Findings table
  lines.push(`## Findings (${findings.length})`);
  lines.push('');
  lines.push('| Severity | Title | Category | Scanner | Location | Fixable | Priority |');
  lines.push('|----------|-------|----------|---------|----------|---------|----------|');

  for (const f of findings) {
    const location = f.file_path
      ? `${f.file_path}${f.line_start ? ':' + f.line_start : ''}`
      : f.endpoint || '-';
    lines.push(`| ${f.severity.toUpperCase()} | ${f.title} | ${f.category} | ${f.scanner} | ${location} | ${f.autofixable ? 'Yes' : 'No'} | ${f.priority_score} |`);
  }
  lines.push('');

  // Finding details
  lines.push('## Finding Details');
  lines.push('');
  for (const f of findings) {
    lines.push(`### ${f.severity.toUpperCase()}: ${f.title}`);
    lines.push('');
    lines.push(`- **Scanner:** ${f.scanner} (${f.scanner_rule_id})`);
    lines.push(`- **Category:** ${f.category}`);
    lines.push(`- **Confidence:** ${f.confidence}`);
    if (f.cwe) lines.push(`- **CWE:** ${f.cwe}`);
    if (f.owasp_mapping) lines.push(`- **OWASP:** ${f.owasp_mapping}`);
    if (f.cvss) lines.push(`- **CVSS:** ${f.cvss}`);
    lines.push('');
    lines.push(f.summary);
    lines.push('');
    if (f.redacted_evidence) {
      lines.push('**Evidence:**');
      lines.push('```');
      lines.push(f.redacted_evidence);
      lines.push('```');
      lines.push('');
    }
    lines.push('**Remediation:**');
    lines.push('');
    lines.push(f.remediation);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push('');
  lines.push('*Generated by SecureScope — Vulnerability Discovery & Remediation Platform*');

  return lines.join('\n');
}
